### ISSUE TITLE
File Naming Between Embedding Generation and Dataset Creation

### ISSUE THREAD

**Issue by felixbusch1** [jordanbehrendt/good_practices_ml#16]
When running generate_embeddings.py, the script outputs CSV files 
in batches with indices appended to the file name, e.g., geoguessr_embeddings_0.csv.

![1](https://github.com/user-attachments/assets/8d80fd25-ae5d-4218-a3a3-5e1814662fc9)

The create_datasets_from_embeddings.py script expects a single CSV file with a simple name, 
such as geoguessr_embeddings.csv.

![2](https://github.com/user-attachments/assets/a812a9a6-2a48-46a8-8832-00ec127c4009)

**Comment by lbrenig** [comment]
This is now updated to use batches in #19.
Try it on the development branch, this should work now
